Vagrant.configure("2") do |config|

  # Ubuntu machines
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.hostname = "ubuntu1"
    
    ubuntu1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.name = "ubuntu1"
      v.cpus = 2
    end
    ubuntu1.vm.provision "shell", inline: <<-SHELL
  # Create a new user named "newuser"
    useradd -m -s /bin/bash ubuntu1
  
  # Set a password for the new user
    echo "ubuntu1:ubuntu1" | chpasswd
SHELL
end

  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/focal64"
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.provider "virtualbox" do |v|
      v.name = "ubuntu2"
      v.memory = 2048
      v.cpus = 2
    end
    ubuntu2.vm.provision "shell", inline: <<-SHELL
  # Create a new user named "newuser"
    useradd -m -s /bin/bash ubuntu2
  
  # Set a password for the new user
    echo "ubuntu2:ubuntu2" | chpasswd
SHELL
  end
  config.vm.define "ubuntu3" do |ubuntu3|
    ubuntu3.vm.box = "ubuntu/focal64"
    ubuntu3.vm.hostname = "ubuntu3"
    
    ubuntu3.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.name = "ubuntu3"
      v.cpus = 2
    end
    ubuntu3.vm.provision "shell", inline: <<-SHELL
  # Create a new user named "newuser"
    useradd -m -s /bin/bash ubuntu3
  # Set a password for the new user
    echo "ubuntu3:ubuntu3" | chpasswd
SHELL
end

  # Red Hat machines
  config.vm.define "redhat1" do |redhat1|
    redhat1.vm.box = "generic/rhel8"
    redhat1.vm.hostname = "redhat1"
    redhat1.vm.provider "virtualbox" do |v|
      v.name = "redhat1"
      v.memory = 2048
      v.cpus = 2
    end
    redhat1.vm.provision "shell", inline: <<-SHELL
    # Set the username and password
    useradd -m -p $(openssl passwd -1 redhatp) -s /bin/bash redhat1

    # Allow password authentication
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

    # Restart sshd
    systemctl restart sshd
  SHELL
  end
end
