Vagrant.configure("2") do |config|

  # Ubuntu machines
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.hostname = "ubuntu1"
    ubuntu1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/focal64"
    ubuntu2.vm.hostname = "ubuntu2"
    ubuntu2.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  # Red Hat machines
  config.vm.define "redhat1" do |redhat1|
    redhat1.vm.box = "generic/redhat8"
    redhat1.vm.hostname = "redhat1"
    redhat1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.define "redhat2" do |redhat2|
    redhat2.vm.box = "generic/redhat8"
    redhat2.vm.hostname = "redhat2"
    redhat2.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end
