# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Specify the box to use
  config.vm.box = "generic/rhel8"
  (1..4).each do |i|
  config.vm.define "redhat#{i}" do |node|
  node.vm.hostname = "redhat#{i}"
  node.vm.network "private_network", ip: "192.168.50.#{i+10}"

 
  # Set the VM hostname
  # config.vm.hostname = "redhat-vm"

  # Set the VM provider to libvirt
  node.vm.provider :virtualbox do |vb|
    vb.name = "redhat#{i}"
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Configure the VM
  node.vm.provision "shell", inline: <<-SHELL
    # Set the username and password
    useradd -m -p $(openssl passwd -1 redhatp) -s /bin/bash redhat

    # Allow password authentication
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

    # Restart sshd
    systemctl restart sshd
  SHELL

end
end
end

