Vagrant.configure("2") do |config|

  # Define Ubuntu VM loop
  (1..3).each do |i|
    config.vm.define "ubuntu#{i}" do |node|
      node.vm.box = "generic/ubuntu2004"
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network "public_network", bridge: "wlp108s0"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "ubuntu#{i}"
        vb.memory = "2048"
        vb.cpus = "2"
      end
  end
end

  # Define RHEL VM loop
  (1..1).each do |i|
    config.vm.define "rhel#{i}" do |node|
      node.vm.box = "generic/rhel8"
      node.vm.hostname = "rhel#{i}"
      node.vm.network "public_network", bridge: "wlp108s0"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "rhel#{i}"
        vb.memory = "2048"
        vb.cpus = "2"
      end
  end
end
end